<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function supprimerUser($id)
    {
//        $em = $this->getDoctrine()->getManager();
//        $query = $this->create(
//            'DELETE StreetBumbApiBundle:BussOwner buss
//               WHERE buss.id = :bussId')
//            ->setParameter("bussId", $id);
//
//        $query->execute();
//
//        $em = $this->getDoctrine()->getManager();
        $qb = $this->createQueryBuilder('u');
        $query = $qb->delete('UserBundle:User', 'u')
            ->where('u.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        $query->execute();

//        $this->createQueryBuilder('t')
//            ->delete('t')
//            ->where('t.id = :id')
//            ->setParameter('id', $id)
//            ->getQuery()->execute();
    }
}
