<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function supprimerUser($id)
    {
        $qb = $this->createQueryBuilder('u');
        $query = $qb->delete('UserBundle:User', 'u')
            ->where('u.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        $query->execute();

    }
}
