<?php
/**
 * Created by PhpStorm.
 * User: Imen BenAbderrahmen
 * Date: 4/11/2018
 * Time: 4:00 AM
 */

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

}
