<?php

namespace EvaluationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends EntityRepository
{
    public function getBoutiquesEvaluees()
    {
        $qb= $this->getEntityManager()->createQueryBuilder();
        $qb->select('IDENTITY(e.idBoutique)')
            ->from('EvaluationBundle:Evaluation', 'e')
            ->distinct('e.idBoutique')
            ->orderBy('e.note', 'DESC')
            ->setMaxResults(5);
        $q = $qb->getQuery();
        return $q->execute();
    }

    public function peutEvaluer($id)
    {
        $result = $this->getEntityManager()->createQuery('SELECT p.idUser FROM SoukBundle:Panier p, SoukBundle:ProduitPanier pp WHERE 
        MONTH(p.idUser) = :id and p.id = : pp.idPanier')
            ->setParameter('id',$id)
            ->getResult();
        return  $result;
    }
}
