<?php

namespace EvaluationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends EntityRepository
{
    public function getBoutiquesEvaluees()
    {
        $qb= $this->getEntityManager()->createQueryBuilder();
        $qb->select('IDENTITY(e.idBoutique)')
            ->from('EvaluationBundle:Evaluation', 'e')
            ->distinct('e.idBoutique')
            ->setMaxResults(5)
            ->orderBy('e.note', 'DESC');
        $q = $qb->getQuery();
        return $q->execute();
    }

    public function getNoteMoyenneuuu($idBoutique)
    {
        $qb= $this->getEntityManager()->createQueryBuilder();
        $qb->select('e.note')
            ->from('EvaluationBundle:Evaluation', 'e')
            ->where('e.idBoutique = :id_boutique')
            ->setParameter('id_boutique',$idBoutique);
        $q = $qb->getQuery();
        return $q->execute();
    }
}
