<?php

namespace EvaluationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends EntityRepository
{

    public function calculerNombre($idBoutique){
        $result = $this->getEntityManager()
            ->createQuery('SELECT e.id_boutique EvaluationBundle:Evaluation e WHERE e.id_boutique =:idBoutique')
            ->setParameter('idBoutique',$idBoutique)
            ->getResult();
        return  $result;
    }

    public function getTopTenBoutiques(){
        $result = $this->getEntityManager()
            ->createQuery('SELECT e.id_boutique EvaluationBundle:Evaluation e WHERE e.id_boutique =:idBoutique')
            ->setParameter('idBoutique',$idBoutique)
            ->getResult();
        return  $result;
    }
}
