reclamation_homepage:
    path:     /
    defaults: { _controller: ReclamationBundle:Default:index }

ajouter_reclamation:
    path:     /ajouter
    defaults: { _controller: ReclamationBundle:Reclamation:ajouterReclamation }
afficher_reclamation:
    path:     /afficher
    defaults: { _controller: ReclamationBundle:Reclamation:afficherReclamation }
supprimer_reclamation:
    path:     /supprimer/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:supprimerReclamation }