ajouter_produit:
    path:     /admin/ajouterProduit
    defaults: { _controller: ProduitBundle:Produit:ajouterProduit }

modifier_produit:
    path:     /admin/modifierProduit{id}
    defaults: { _controller: ProduitBundle:Produit:modifierProduit }

supprimer_produit:
    path:     /admin/supprimerProduit{id}
    defaults: { _controller: ProduitBundle:Produit:supprimerProduit }

afficher_produits:
    path:     /admin/afficherProduits
    defaults: { _controller: ProduitBundle:Produit:afficherProduit }

afficher_front_produit:
    path:     /Produits
    defaults: { _controller: ProduitBundle:Produit:afficherFrontProduit }

ajouter_categorie:
    path:     /admin/ajouterCategorie
    defaults: { _controller: ProduitBundle:Categorie:ajoutercategorie }

modifier_categorie:
    path:     /admin/modifierCategorie{id}
    defaults: { _controller: ProduitBundle:Categorie:modifiercategorie }

supprimer_categorie:
    path:     /admin/supprimerCategorie{id}
    defaults: { _controller: ProduitBundle:Categorie:supprimerCategorie }

afficher_categorie:
    path:     /admin/afficherCategorie
    defaults: { _controller: ProduitBundle:Categorie:afficherCategorie }

afficher_produit_details:
    path:     /afficherProduitDetail/{id}
    defaults: { _controller: ProduitBundle:Produit:afficherProduitDetail }






