ajouter_boutique:
    path:     /ajouterBoutique
    defaults: { _controller: BoutiqueBundle:Boutique:ajouterBoutique }
afficher_boutique:
    path:     /
    defaults: { _controller: BoutiqueBundle:Boutique:afficherBoutique }
modifier_boutique:
    path:     /modifier/{id}
    defaults: { _controller: BoutiqueBundle:Boutique:modifierBoutique }
supprimer_boutique:
    path:     /supprimer/{id}
    defaults: { _controller: BoutiqueBundle:Boutique:supprimerBoutique }
details_boutique:
    path:     /details/{id}
    defaults: { _controller: BoutiqueBundle:Boutique:afficherBoutiqueDetail }
afficher_boutique_artisan:
    path:     /afficherArtisan/{id}
    defaults: { _controller: BoutiqueBundle:Boutique:afficherBoutiqueArtisan }
chercher_boutique:
    path:     /chercher
    defaults: { _controller: BoutiqueBundle:Boutique:chercherBoutique }
