ajouter_boutique:
    path:     /ajouterBoutique
    defaults: { _controller: BoutiqueBundle:Boutique:ajouterBoutique }
afficher_boutique:
    path:     /
    defaults: { _controller: BoutiqueBundle:Boutique:afficherBoutique }
