afficher_statAdminB:
    path:     /afficherAdminB
    defaults: { _controller: StatistiqueBundle:Statistique:afficherStatistiqueAdminB }
afficher_statAdminU:
    path:     /afficherAdminU
    defaults: { _controller: StatistiqueBundle:Statistique:afficherStatistiqueAdminU }