<<<<<<< HEAD
boutique:
    resource: "@BoutiqueBundle/Controller/"
    type:     annotation
    prefix:   /
=======
tombola:
    resource: "@TombolaBundle/Controller/"
    type:     annotation
    prefix:   /tombola
>>>>>>> b8329328cacbfdd19a13864175397d6b54d9de04

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

souk:
#    resource: "@SoukBundle/Resources/config/routing.yml"
    resource: "@SoukBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

