
panier:
    resource: "@PanierBundle/Controller/"
    type:     annotation
    prefix:   /panier

statistique:
    resource: "@StatistiqueBundle/Resources/config/routing.yml"
    prefix:   /statistique



historique:
    resource: "@HistoriqueBundle/Resources/config/routing.yml"
    prefix:   /historique

evaluation:
    resource: "@EvaluationBundle/Resources/config/routing.yml"
    prefix:   /evaluation


produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /


boutique:
    resource: "@BoutiqueBundle/Resources/config/routing.yml"
    prefix:   /boutique

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation

#boutique:
#    resource: "@BoutiqueBundle/Controller/"
#    type:     annotation
#    prefix:   /



tombola:
    resource: "@TombolaBundle/Controller/"
    type:     annotation
    prefix:   /tombola


user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

souk:
    resource: "@SoukBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

