<<<<<<< HEAD
produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /

=======
boutique:
    resource: "@BoutiqueBundle/Resources/config/routing.yml"
    prefix:   /boutique

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation

boutique:
    resource: "@BoutiqueBundle/Controller/"
    type:     annotation
    prefix:   /
>>>>>>> 2b4bb802c6cdc81c1ab467e44b187345fbd6d1e9

tombola:
    resource: "@TombolaBundle/Controller/"
    type:     annotation
    prefix:   /tombola


user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

souk:
#    resource: "@SoukBundle/Resources/config/routing.yml"
    resource: "@SoukBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

