<<<<<<< HEAD

boutique:
    resource: "@BoutiqueBundle/Resources/config/routing.yml"
    prefix:   /boutique

=======
<<<<<<< HEAD
reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation

=======
<<<<<<< HEAD
boutique:
    resource: "@BoutiqueBundle/Controller/"
    type:     annotation
    prefix:   /
=======
>>>>>>> 837629ee8fb9df79aea9515483010cd8c3eeeaaa
>>>>>>> 3a68fe4ba2bccc0920b92d049dad142e7c687edd
tombola:
    resource: "@TombolaBundle/Controller/"
    type:     annotation
    prefix:   /tombola


user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

souk:
#    resource: "@SoukBundle/Resources/config/routing.yml"
    resource: "@SoukBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

