<<<<<<< HEAD

=======
>>>>>>> f0a45c7f3f909ebc7767fe9fbbe9f65b40d635b4
panier:
    resource: "@PanierBundle/Controller/"
    type:     annotation
    prefix:   /panier

statistique:
    resource: "@StatistiqueBundle/Resources/config/routing.yml"
    prefix:   /statistique

historique:
    resource: "@HistoriqueBundle/Resources/config/routing.yml"
    prefix:   /historique

evaluation:
    resource: "@EvaluationBundle/Resources/config/routing.yml"
    prefix:   /evaluation

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /

boutique:
    resource: "@BoutiqueBundle/Resources/config/routing.yml"
    prefix:   /boutique

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation

<<<<<<< HEAD
=======
#boutique:
#    resource: "@BoutiqueBundle/Controller/"
#    type:     annotation
#    prefix:   /


>>>>>>> f0a45c7f3f909ebc7767fe9fbbe9f65b40d635b4
tombola:
    resource: "@TombolaBundle/Controller/"
    type:     annotation
    prefix:   /tombola

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

souk:
    resource: "@SoukBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

